Batched Rendering
IceSDK/IceSDK pull request #36
Opened 2020-10-14 17:58 UTC by loanselot1

Progess for #32

2020-10-15 06:21 UTC, Mempler requested changes
Please change those things before we can consider to merge this.

2020-10-15 06:21 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.cc
> +static std::array<glm::vec2, QUAD_COUNT> _def_tex_coords = {
Since this is a global variable, this should be renamed to `g_DefTexCoords`

2020-10-15 06:21 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
> +        void SubmitTexturedQuad(Memory::Ptr<Texture2D> texture, const glm::vec2 &position, const glm::vec2 &size, const glm::vec4 &color);
Parameters must be pName, E.G `pTexture`

2020-10-15 06:21 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
> +        void DrawIndexed(glm::mat4 transform, glm::vec4 vertex_pos[QUAD_COUNT],
Parameters must be pName, E.G `pTexture`

2020-10-15 06:21 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
> +        static const uint32_t max_quads = 20000;
All private members must start with _ and be lowUpper case. E.G `_MaxQuads`

2020-10-15 17:41 UTC, Mempler requested changes

2020-10-15 17:41 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
> +        void SubmitTexturedQuad(Memory::Ptr<Texture2D> pTexture, const glm::vec2 &position, const glm::vec2 &size, const glm::vec4 &color);
Wrong style on `position`, `size` and `color`

2020-10-15 17:41 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
>          void DrawIndexed(glm::mat4 transform, glm::vec4 vertex_pos[QUAD_COUNT],
Wrong style on `transform`, `vertex_pos`

2020-10-17 14:39 UTC, loanselot1 commented
wow #undef mix

2020-10-17 14:58 UTC, Mempler requested changes

2020-10-17 14:58 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
> +    namespace Graphics
use namespace `IceSDK::Graphics` instead. we use C++17 styled namespaces

2020-10-17 14:58 UTC, Mempler commented on IceSDK/Graphics/SpriteBatch/SpriteBatch.h
> +                             uint32_t index_count = 6);
Wrong name scheme `transform`, `vertex_pos`, `uvs`, `texture_id`, `index_count`

2020-10-17 15:03 UTC, Mempler approved these changes

2020-10-17 15:11 UTC, merged